/* Quiz V2 — Stable + Premium */
let finalCorrect=0,finalWrong=0,finalScore=0;
let selectedCategory="",currentQuestion=0,quizQuestions=[],userAnswers=[],quizTime=600,timer=null,endTime=0,canAnswer=true,quizFinished=false;
const correctSound=document.getElementById("correctSound"),wrongSound=document.getElementById("wrongSound"),answerStatus=document.getElementById("answerStatus"),quizSection=document.getElementById("quiz-section"),resultSection=document.getElementById("result-section"),questionText=document.getElementById("questionText"),optionContainer=document.getElementById("optionContainer"),quizCategory=document.getElementById("quizCategory"),quizTimer=document.getElementById("quizTimer");
async function startQuiz(category){selectedCategory=category;const questions=await loadQuestions(category);if(!questions.length){alert("এই ক্যাটাগরিতে এখনো কোনো প্রশ্ন নেই।");return}quizQuestions=questions;currentQuestion=0;userAnswers=[];quizTime=600;canAnswer=true;quizFinished=false;document.getElementById("category-section")?.classList.add("hidden");document.getElementById("top-three")?.classList.add("hidden");quizSection?.classList.remove("hidden");resultSection?.classList.add("hidden");startTimer();showQuestion()}
function showQuestion(){const q=quizQuestions[currentQuestion];if(!q)return;canAnswer=true;hideAnswerStatus();enableButtons();quizCategory.textContent=selectedCategory;questionText.textContent=`${currentQuestion+1}. ${q.question}`;optionContainer.innerHTML="";shuffleArray([...q.options]).forEach(option=>{const b=document.createElement("button");b.type="button";b.className="option-btn";b.textContent=option;b.onclick=()=>selectAnswer(b,option);optionContainer.appendChild(b)});restoreAnswer()}
function restoreAnswer(){const saved=userAnswers[currentQuestion];if(saved===undefined)return;document.querySelectorAll(".option-btn").forEach(b=>{if(b.textContent.trim()===String(saved).trim())b.classList.add("selected")})}
function selectAnswer(button,answer){if(!canAnswer||quizFinished)return;canAnswer=false;userAnswers[currentQuestion]=answer;disableButtons();const q=quizQuestions[currentQuestion];document.querySelectorAll(".option-btn").forEach(b=>{const t=b.textContent.trim();if(t===q.answer)b.classList.add("correct");if(t===answer&&answer!==q.answer)b.classList.add("wrong")});const ok=answer===q.answer,sound=ok?correctSound:wrongSound;if(sound){sound.currentTime=0;sound.play().catch(()=>{})}showAnswerStatus(ok?"✔️ Correct!":"❌ Wrong!",ok?"correct":"wrong");setTimeout(()=>{if(quizFinished)return;if(currentQuestion<quizQuestions.length-1){currentQuestion++;showQuestion()}else finishQuiz()},850)}
function startTimer(){clearInterval(timer);endTime=Date.now()+quizTime*1000;updateTimer();timer=setInterval(updateTimer,250)}
function updateTimer(){const remaining=Math.max(0,Math.ceil((endTime-Date.now())/1000));quizTime=remaining;if(quizTimer)quizTimer.textContent=`⏱️ ${String(Math.floor(remaining/60)).padStart(2,"0")}:${String(remaining%60).padStart(2,"0")}`;if(remaining<=0){clearInterval(timer);finishQuiz()}}
function stopTimer(){clearInterval(timer);timer=null}
async function finishQuiz(){if(quizFinished)return;quizFinished=true;canAnswer=false;stopTimer();disableButtons();let correct=0,wrong=0,skipped=0;quizQuestions.forEach((q,i)=>{const a=userAnswers[i];if(a===undefined||a===null||a==="")skipped++;else if(a===q.answer)correct++;else wrong++});const score=correct;finalCorrect=correct;finalWrong=wrong;finalScore=score;const elapsed=Math.max(0,600-quizTime);await saveLeaderboard({score,correct,wrong,skipped,time:elapsed,category:selectedCategory});quizSection?.classList.add("hidden");resultSection?.classList.remove("hidden");const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set("correctAnswer",correct);set("wrongAnswer",wrong);set("finalScore",score);const badge=document.getElementById("levelBadge");if(badge){const p=quizQuestions.length?Math.round(score/quizQuestions.length*100):0;const level=p>=90?["🏆 Expert","level-expert"]:p>=70?["🥇 Advanced","level-advanced"]:p>=50?["🥈 Intermediate","level-intermediate"]:p>=30?["🥉 Beginner","level-beginner"]:["📘 Practice More","level-practice"];badge.className=`level-badge ${level[1]}`;badge.textContent=level[0]}localStorage.setItem("quizLastResult",JSON.stringify({category:selectedCategory,score,correct,wrong,skipped,percentage:quizQuestions.length?Math.round(score/quizQuestions.length*100):0,at:Date.now()}))}
document.getElementById("nextBtn")?.addEventListener("click",()=>{if(currentQuestion<quizQuestions.length-1){currentQuestion++;showQuestion()}});document.getElementById("prevBtn")?.addEventListener("click",()=>{if(currentQuestion>0){currentQuestion--;showQuestion()}});document.getElementById("finishBtn")?.addEventListener("click",()=>{if(!quizFinished&&confirm("আপনি কি কুইজ শেষ করতে চান?"))finishQuiz()});document.getElementById("playAgainBtn")?.addEventListener("click",()=>{resetQuiz();resultSection?.classList.add("hidden");document.getElementById("category-section")?.classList.remove("hidden");document.getElementById("top-three")?.classList.remove("hidden")});document.getElementById("homeBtn")?.addEventListener("click",()=>location.reload());
function resetQuiz(){stopTimer();selectedCategory="";currentQuestion=0;quizQuestions=[];userAnswers=[];quizTime=600;endTime=0;canAnswer=true;quizFinished=false;hideAnswerStatus()}
function showAnswerStatus(message,type){if(!answerStatus)return;answerStatus.className=`answer-status ${type}`;answerStatus.textContent=message}function hideAnswerStatus(){if(answerStatus)answerStatus.className="answer-status hidden"}function enableButtons(){document.querySelectorAll(".option-btn").forEach(b=>b.disabled=false)}function disableButtons(){document.querySelectorAll(".option-btn").forEach(b=>b.disabled=true)}
async function shareScore(){const text=`🎉 আমি Quiz Of AKTER SIR-এ ${finalScore} Score করেছি!\n\n✅ Correct : ${finalCorrect}\n❌ Wrong : ${finalWrong}\n\nতুমিও খেলো 👇\nhttps://hunter09090.github.io/Akter-Sir-/`;try{if(navigator.share)await navigator.share({title:"Quiz Of AKTER SIR",text});else{await navigator.clipboard.writeText(text);alert("✅ Score copied to clipboard!")}}catch(e){console.log("Share cancelled",e)}}
document.addEventListener("DOMContentLoaded",()=>document.getElementById("shareBtn")?.addEventListener("click",shareScore));